name: Build & Test

on:
  pull_request:
    branches: [ master-dev ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - run: npm install
        working-directory: ./live-core
      - run: npm test
        working-directory: ./live-core
